[theme]
# The main background color
backgroundColor = "#310140"

# The color of text on the main background
textColor = "#FFFFFF"

# The font for the entire app. Streamlit will import it from Google Fonts.
font = "Comic Relief"
